# Generated by Django 5.0.4 on 2024-06-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_alter_city_name_alter_shop_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="city",
        ),
        migrations.AddField(
            model_name="shop",
            name="city",
            field=models.ManyToManyField(blank=True, to="shops.city"),
        ),
    ]
