# Generated by Django 5.0.4 on 2024-06-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_remove_shop_city_shop_city"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="City",
            new_name="Address",
        ),
    ]
