# Generated by Django 5.0.4 on 2024-06-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_rename_city_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="city",
            new_name="address",
        ),
    ]
